services:
  opa:
    image: openpolicyagent/opa:latest
    ports:
      - "8181:8181"
    volumes:
      - ./policy.rego:/policy.rego
    command:
      - "run"
      - "--server"
      - "/policy.rego"
