server:
  port: 1001
spring:
  application:
    name: micro-auth
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:2001/eureka/
  data:
    redis:
      host: localhost
      port: 6379